DEV_NAME = '/dev/frio0'

ANML_PATH = 'anml'
FSM_PATH = 'fsm'
MAP_PATH = 'map'
DATA_PATH = 'datasets'

DEFAULT_DELIM = 255
DEFAULT_SYMBOL = '*'
DEFAULT_TARGET = 1
DEFAULT_CHUNK_SZ = 512

BLK_PER_DEV = 192
BLK_PER_RANK = BLK_PER_DEV * 8
STE_ID_SPACE = 255
MAX_SINGLE_TARGET = 2**11
MAX_DOUBLE_TARGET = MAX_SINGLE_TARGET**2

COMPILE_TIMEOUT = 300
